package ar.com.netmefy.netmefy.router;

/**
 * Created by fiok on 22/07/2017.
 */

public enum eUrl {
    LOGIN,
    WIFI_GET_SSID,
    WIFI_GET_PASSWORD,
    WIFI_SET_SSID,
    WIFI_SET_PASSWORD,
    RESTART,
    LIST_CONNECTED,
    WIFI_SET_SSID_TO_GET_SESSIONKEY,
    WIFI_SET_PASSWORD_TO_GET_SESSIONKEY,
    RESTART_TO_GET_SESSIONKEY,
    ADD_BLOCK_BY_MAC,
    ADD_BLOCK_BY_MAC_TO_GET_SESSIONKEY,
    LOGOUT,
    REMOVE_BLOCK_BY_MAC,
    REMOVE_BLOCK_BY_MAC_TO_GET_SESSIONKEY

}
